# Generated by Django 4.0.6 on 2022-07-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshots',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='carsapp.cars'),
        ),
    ]
