# Generated by Django 4.0.6 on 2022-08-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_alter_cashshots_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashShots',
            new_name='CarsShots',
        ),
    ]
